Body_Site(description='Adrenal Glands', parent=None, umls_id='C0001625').save()
Body_Site(description='Anus', parent=None, umls_id='C0003461').save()
Body_Site(description='Appendix', parent=None, umls_id='C0003617').save()
Body_Site(description='Urinary Bladder', parent=None, umls_id='C0005682').save()
Body_Site(description='Biliary tract structure', parent=None, umls_id='C0005423').save()
Body_Site(description='bone and joint', parent=None, umls_id='C0545594').save()
Body_Site(description='Mucocele of appendix', parent=None, umls_id='C0026684').save()
Body_Site(description='Axial', parent=None, umls_id='C0205131').save()
Body_Site(description='Bone structure of cranium', parent=None, umls_id='C0037303').save()
Body_Site(description='Gnathic osteosarcoma', parent=None, umls_id='C3494968').save()
Body_Site(description='Bone Marrow', parent=None, umls_id='C0005953').save()
Body_Site(description='Central Nervous System Stimulants', parent=None, umls_id='C0002763').save()
Body_Site(description='Brain', parent=None, umls_id='C0006104').save()
Body_Site(description='Meninges', parent=None, umls_id='C0025285').save()
Body_Site(description='Spinal Cord', parent=None, umls_id='C0037925').save()
Body_Site(description='Breast', parent=None, umls_id='C0006141').save()
Body_Site(description='Intestine - Large Intestine - Colon (MMHCC)', parent=None, umls_id='C1522281').save()
Body_Site(description='Esophagus', parent=None, umls_id='C0014876').save()
Body_Site(description='Fallopian Tubes', parent=None, umls_id='C0015560').save()
Body_Site(description='Gallbladder', parent=None, umls_id='C0016976').save()
Body_Site(description='Head and neck structure', parent=None, umls_id='C0460004').save()
Body_Site(description='Eye/Orbit', parent=None, umls_id='C3846141').save()
Body_Site(description='Laryngeal Diseases', parent=None, umls_id='C0023051').save()
Body_Site(description='Parathyroid gland', parent=None, umls_id='C0030518').save()
Body_Site(description='Pharyngeal structure', parent=None, umls_id='C0031354').save()
Body_Site(description='Skin Specimen', parent=None, umls_id='C0444099').save()
Body_Site(description='Thyroid Gland', parent=None, umls_id='C0040132').save()
Body_Site(description='Blood vessel of heart', parent=None, umls_id='C3686473').save()
Body_Site(description='Kidney', parent=None, umls_id='C0022646').save()
Body_Site(description='Liver', parent=None, umls_id='C0023884').save()
Body_Site(description='Lung', parent=None, umls_id='C0024109').save()
Body_Site(description='lymph nodes', parent=None, umls_id='C0024204').save()
Body_Site(description='Mediastinum', parent=None, umls_id='C0025066').save()
Body_Site(description='Thymus Extracts', parent=None, umls_id='C0040112').save()
Body_Site(description='Other', parent=None, umls_id='C0205394').save()
Body_Site(description='Diseases and Syndromes of Peritoneum, Omentum and Mesentery', parent=None, umls_id='C0541426').save()
Body_Site(description='Ovary', parent=None, umls_id='C0029939').save()
Body_Site(description='Pancreas', parent=None, umls_id='C0030274').save()
Body_Site(description='penis', parent=None, umls_id='C0030851').save()
Body_Site(description='Pleura', parent=None, umls_id='C0032225').save()
Body_Site(description='Rectum', parent=None, umls_id='C0034896').save()
Body_Site(description='Salivary Glands', parent=None, umls_id='C0036098').save()
Body_Site(description='small intestine and small intestine', parent=None, umls_id='C0545833').save()
Body_Site(description='Duodenum', parent=None, umls_id='C0013303').save()
Body_Site(description='Jejunum', parent=None, umls_id='C0022378').save()
Body_Site(description='ileum', parent=None, umls_id='C0020885').save()
Body_Site(description='soft tissue', parent=None, umls_id='C0225317').save()
Body_Site(description='Head and neck structure', parent=None, umls_id='C0460004').save()
Body_Site(description='Superficial Soft Tissue Fibrosis', parent=None, umls_id='C1698669').save()
Body_Site(description='Retroperitoneal Space', parent=None, umls_id='C0035359').save()
Body_Site(description='Spleen', parent=None, umls_id='C0037993').save()
Body_Site(description='Stomach', parent=None, umls_id='C0038351').save()
Body_Site(description='Testis', parent=None, umls_id='C0039597').save()
Body_Site(description='Prostate', parent=None, umls_id='C0033572').save()
Body_Site(description='Ureter', parent=None, umls_id='C0041951').save()
Body_Site(description='Uterus', parent=None, umls_id='C0042149').save()
Body_Site(description='Cervix Uteri', parent=None, umls_id='C0007874').save()
Body_Site(description='Endometrium', parent=None, umls_id='C0014180').save()
Body_Site(description='myometrium', parent=None, umls_id='C0027088').save()
Body_Site(description='Vagina', parent=None, umls_id='C0042232').save()
Body_Site(description='Vulva', parent=None, umls_id='C0042993').save()